[project]
name = "thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fiftyone>=1.9.0",
    "gdown>=5.2.0",
    "infisicalsdk>=1.0.11",
    "torch>=2.9.0",
]
