_BASE_RUN: ../../pool/run/training/finetune.yaml
_BASE_MODEL: ../../pool/backbone/tadaformer_l14_soccer.yaml

PRETRAIN:
  ENABLE: false
TRAIN:
  ENABLE: true
  DATASET: Mvfoul
  BATCH_SIZE: 3
  FINE_TUNE: true
  LR_REDUCE: true
  INIT: clip
  CHECKPOINT_FILE_PATH: "/Volumes/KG1TB/Developement/thesis/l14_clip_k710.pyth"
TEST:
  ENABLE: true
  DATASET: MVFoul
  BATCH_SIZE: 8
DATA:
  DATA_ROOT_DIR: /Volumes/KG1TB/data/SoccerData/mvfouls
  ANNO_DIR:
  SAMPLING_MODE: segment_based
  NUM_INPUT_FRAMES: 16
  NUM_VIEWS: 2
  TRAIN_JITTER_SCALES: [0.08, 1.0]
  TRAIN_CROP_SIZE: 224
  TEST_SCALE: 224
  TEST_CROP_SIZE: 224
  MEAN: [0.48145466, 0.4578275, 0.40821073]
  STD: [0.26862954, 0.26130258, 0.27577711]
VIDEO:
  HEAD:
    NUM_CLASSES: [4, 8]
    DROPOUT_RATE: 0

OUTPUT_DIR: output/tadaformer_l14_k400_16f

OPTIMIZER:
  BASE_LR: 2e-5
  ADJUST_LR: false
  LR_POLICY: cosine_v2
  COSINE_END_LR: 1e-6
  COSINE_AFTER_WARMUP: true
  MAX_EPOCH: 24
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.05
  WARMUP_EPOCHS: 5
  WARMUP_START_LR: 1e-6
  OPTIM_METHOD: adamw
  DAMPENING: 0.0
  NESTEROV: true
  HEAD_LRMULT: 10
  NEW_PARAMS: ["tada"]
  NEW_PARAMS_MULT: 10
  LAYER_WISE_LR_DECAY: 0.85
AUGMENTATION: 
  COLOR_AUG: true
  GRAYSCALE: 0.2
  COLOR_P: 0.0
  CONSISTENT: true
  SHUFFLE: true
  GRAY_FIRST: false
  IS_SPLIT: false
  USE_GPU: false
  SSV2_FLIP: true
  RATIO: [0.75, 1.333]
  MIXUP: 
    ENABLE: false
  CUTMIX: 
    ENABLE: false
  RANDOM_ERASING:
    ENABLE: false
  LABEL_SMOOTHING: 0.1
  AUTOAUGMENT:
    ENABLE: true
    BEFORE_CROP: true
    TYPE: rand-m9-n4-mstd0.5-inc1
NUM_GPUS: 0
DATA_LOADER:
  NUM_WORKERS: 1
  PIN_MEMORY: false